language: go
go:
  - 1.7

script:
   - apt-get install -y libgtk-3-0
   - go build
deploy:
  provider: releases
  api_key: "${GH_DEPLOY_KEY}"
  file: "go-md5sum-ui"
  skip_cleanup: true
  on:
    tags: true