dist: trusty
sudo: required

language: go
go:
  - 1.7
before_install:
  - sudo apt-get install -y libgtk-3-dev
  - go get -d -v -t
script:
  - go build
deploy:
  provider: releases
  api_key: "${GH_DEPLOY_KEY}"
  file: "go-md5sum-ui"
  skip_cleanup: true
  on:
    tags: true
